version: '3.4'

services:
  identity-server-sts:
    build:
      context: ./aspnet-core/services/Publish/identityserver
    volumes:
      - /var/opt/abp/logs/ids-sts:/app/Logs
      - /var/opt/abp/data/ids-sts/Modules:/app/Modules
    restart: always

  identity-server-admin:
    build:
      context: ./aspnet-core/services/Publish/identityserver4-admin
    volumes:
      - /var/opt/abp/logs/ids-admin:/app/Logs
      - /var/opt/abp/data/ids-admin/Modules:/app/Modules
    depends_on:
      - identity-server-sts
    restart: always

  admin-service:
    build:
      context: ./aspnet-core/services/Publish/admin
    volumes:
      - /var/opt/abp/logs/backend-admin:/app/Logs
      - /var/opt/abp/data/backend-admin/Modules:/app/Modules
    depends_on:
      - identity-server-sts
    restart: always

  localization-service:
    build:
      context: ./aspnet-core/services/Publish/localization
    volumes:
      - /var/opt/abp/logs/localization:/app/Logs
      - /var/opt/abp/data/localization/Modules:/app/Modules
    restart: always

  platform-service:
    build:
      context: ./aspnet-core/services/Publish/platform
    volumes:
      - /var/opt/abp/logs/platform:/app/Logs
      - /var/opt/abp/data/platform/Modules:/app/Modules
      - /var/opt/abp/data/platform:/app/file-blob-storing
    depends_on:
      - identity-server-sts
    restart: always

  messages-service:
    build:
      context: ./aspnet-core/services/Publish/messages
    volumes:
      - /var/opt/abp/logs/messages:/app/Logs
      - /var/opt/abp/data/messages/Modules:/app/Modules
    depends_on:
      - identity-server-sts
    restart: always

  internat-apigateway:
    build:
      context: ./gateways/internal/LINGYUN.MicroService.Internal.ApiGateway/src/LINGYUN.MicroService.Internal.ApiGateway
    volumes:
      - /var/opt/abp/logs/internat-apigateway:/app/Logs
      - /var/opt/abp/data/internat-apigateway/Modules:/app/Modules
    restart: always

volumes:
  dbdata:

networks:
  linyun-abp:
