version: '3.4'

services:
  sts-server:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.AuthServer
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=AuthServer
      - AgileConfig__tag=AuthServer

  sts-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.IdentityServer.Admin
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=IdentityServer.Admin
      - AgileConfig__tag=IdentityServer.Admin

  admin-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Backend.Admin
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=BackendAdmin
      - AgileConfig__tag=BackendAdmin

  localization-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Localization
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=Localization
      - AgileConfig__tag=Localization

  platform-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Platform
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=Platform
      - AgileConfig__tag=Platform

  messages-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Message
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=Message
      - AgileConfig__tag=Message

  task-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Task
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=Task
      - AgileConfig__tag=Task

  webhook-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Webhooks
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=Webhooks
      - AgileConfig__tag=Webhooks

  workflow-api:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Abp.Workflow
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=Workflow
      - AgileConfig__tag=Workflow

  internal-apigateway:
    environment:
      - AgileConfig__IsEnabled=true
      - AgileConfig__env=DEV
      - AgileConfig__appId=LINGYUN.Internal.ApiGateway
      - AgileConfig__secret=1q2w3E*
      - AgileConfig__nodes=http://docker.gzbit.cn:5000
      - AgileConfig__name=ApiGateway
      - AgileConfig__tag=ApiGateway
