version: '3.4'

services:
  identity-server-sts:
    build:
      context: ./aspnet-core/services/Publish/identityserver
    volumes:
      - /var/opt/abp/logs/ids-sts:/app/Logs
    restart: always

  identity-server-admin:
    build:
      context: ./aspnet-core/services/Publish/identityserver4-admin
    volumes:
      - /var/opt/abp/logs/ids-admin:/app/Logs
    depends_on:
      - identity-server-sts
    restart: always

  admin-service:
    build:
      context: ./aspnet-core/services/Publish/admin
    volumes:
      - /var/opt/abp/logs/backend-admin:/app/Logs
      - /var/opt/abp/data/backend-admin/Modules:/app/Modules
    depends_on:
      - identity-server-sts
    restart: always

  localization-service:
    build:
      context: ./aspnet-core/services/Publish/localization
    volumes:
      - /var/opt/abp/logs/localization:/app/Logs
    restart: always

  platform-service:
    build:
      context: ./aspnet-core/services/Publish/platform
    volumes:
      - /var/opt/abp/logs/platform:/app/Logs
      - /var/opt/abp/data/platform:/app/file-blob-storing
    depends_on:
      - identity-server-sts
    restart: always

  messages-service:
    build:
      context: ./aspnet-core/services/Publish/messages
    volumes:
      - /var/opt/abp/logs/messages:/app/Logs
    depends_on:
      - identity-server-sts
    restart: always

  apigateway-admin-service:
    build:
      context: ./aspnet-core/services/Publish/apigateway-admin
    volumes:
      - /var/opt/abp/logs/apigateway-admin:/app/Logs
    depends_on:
      - identity-server-sts
      - admin-service
    restart: always

  apigateway-host-service:
    build:
      context: ./aspnet-core/services/Publish/apigateway-host
    volumes:
      - /var/opt/abp/logs/apigateway-host:/app/Logs
    depends_on:
      - identity-server-sts
      - apigateway-admin-service
    restart: always

volumes:
  dbdata:

networks:
  linyun-abp:
